# algorithm parameter
FLASH:
  # LiDAR FoV (unit degree)   (it is to survive fibonacci anchor in FoV )
  fov_left: -180.0
  fov_right: 180.0
  fov_down: -24.8 
  fov_up: 2.0

  # Avia     :  H = 70.4
  #          :  V = -38.6 ~ 38.6 
  # HDL-64   :  H = 360.0
  #          :  V = -24.8 ~ 2.0
  # OS1-64   :  H = 360.0
  #          :  V = -22.5 ~ 22.5
  # OS2-128  :  H = 360.0
  #          :  V = -11.25 ~ 11.25

  # global descriptor parameter
  leaf_size : 0.2  # 0.2 # if set 0 => disable
  edge_th : 200.0
  num_hop : 3
  num_anchor : 2048 # 8192 # 4096 # only used in initailized fibonacci lattice / only anchors within the FoV are used
  l : 7 # degree for spherical harmonics
  
  # verification parameter
  inlier_th : 0 # Minimum number of inliers; if 0, all candidates are returned
  similarity_th : -1.0   # you can easily add similarity threshold; if -1, all candidates are returned
  
  use_precomputed_wl_map : false
  precomputed_wl_map_path : "" # not use

  # If you want to add another label, be sure to update all three entries accordingly. (target, eps, min_pts)
  foreground_label:
    # 10 : "car"
    # 20 : "other-vehicle"
    50 : "building"
    51 : "fence"
    70 : "vegetation"
    71 : "trunk"
    72 : "terrain"
    80 : "pole"
    81 : "traffic-sign"

  background_label:
    40 : "road"
    48 : "sidewalk"
    49 : "other-ground"
    50 : "building"
    51 : "fence"
    72 : "terrain"

  eps_per_label:
    10 : 1.0
    20 : 1.0
    48 : 1.0
    50 : 1.0
    51 : 1.0
    70 : 1.0
    71 : 1.0
    72 : 1.0
    80 : 1.0
    81 : 1.0

  min_pts_per_label:
    10 : 30
    20 : 30
    48 : 50
    50 : 50
    51 : 20
    70 : 50
    71 : 10
    72 : 80
    80 : 10
    81 : 10

  color_map:  # RGB
    0:   [0, 0, 0]
    1:   [255, 0, 0]
    10:  [100, 150, 245]
    11:  [100, 230, 245]
    13:  [100, 80, 250]
    15:  [30, 60, 150]
    16:  [0, 0, 255]
    18:  [80, 30, 180]
    20:  [0, 0, 255]
    30:  [255, 30, 30]
    31:  [255, 40, 200]
    32:  [150, 30, 90]
    40:  [255, 0, 255]
    44:  [255, 150, 255]
    48:  [75, 0, 75]
    49:  [175, 0, 75]
    50:  [255, 200, 0]
    51:  [255, 120, 50]
    52:  [255, 150, 0]
    60:  [150, 255, 170]
    70:  [0, 175, 0]
    71:  [135, 60, 0]
    72:  [150, 240, 80]
    80:  [255, 240, 150]
    81:  [255, 0, 0]
    99:  [50, 255, 255]
    252: [100, 150, 245]
    256: [0, 0, 255]
    253: [255, 40, 200]
    254: [255, 30, 30]
    255: [150, 30, 90]
    257: [100, 80, 250]
    258: [80, 30, 180]
    259: [0, 0, 255]

  # color_map: # bgr
  #   0 : [0, 0, 0]
  #   1 : [0, 0, 255]
  #   10: [245, 150, 100]
  #   11: [245, 230, 100]
  #   13: [250, 80, 100]
  #   15: [150, 60, 30]
  #   16: [255, 0, 0]
  #   18: [180, 30, 80]
  #   20: [255, 0, 0]
  #   30: [30, 30, 255]
  #   31: [200, 40, 255]
  #   32: [90, 30, 150]
  #   40: [255, 0, 255]
  #   44: [255, 150, 255]
  #   48: [75, 0, 75]
  #   49: [75, 0, 175]
  #   50: [0, 200, 255]
  #   51: [50, 120, 255]
  #   52: [0, 150, 255]
  #   60: [170, 255, 150]
  #   70: [0, 175, 0]
  #   71: [0, 60, 135]
  #   72: [80, 240, 150]
  #   80: [150, 240, 255]
  #   81: [0, 0, 255]
  #   99: [255, 255, 50]
  #   252: [245, 150, 100]
  #   256: [255, 0, 0]
  #   253: [200, 40, 255]
  #   254: [30, 30, 255]
  #   255: [90, 30, 150]
  #   257: [250, 80, 100]
  #   258: [180, 30, 80]
  #   259: [255, 0, 0]


  # semantic kitti labels
  # 0 : "unlabeled"
  # 1 : "outlier"
  # 10: "car"
  # 11: "bicycle"
  # 13: "bus"
  # 15: "motorcycle"
  # 16: "on-rails"
  # 18: "truck"
  # 20: "other-vehicle"
  # 30: "person"
  # 31: "bicyclist"
  # 32: "motorcyclist"
  # 40: "road"
  # 44: "parking"
  # 48: "sidewalk"
  # 49: "other-ground"
  # 50: "building"
  # 51: "fence"
  # 52: "other-structure"
  # 60: "lane-marking"
  # 70: "vegetation"
  # 71: "trunk"
  # 72: "terrain"
  # 80: "pole"
  # 81: "traffic-sign"
  # 99: "other-object"
  # 252: "moving-car"
  # 253: "moving-bicyclist"
  # 254: "moving-person"
  # 255: "moving-motorcyclist"
  # 256: "moving-on-rails"
  # 257: "moving-bus"
  # 258: "moving-truck"
  # 259: "moving-other-vehicle"
